name: kc_verifier
description: karmacoin verifier
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  firebase_admin: ^0.2.0
  ed25519_edwards: ^0.3.1
  quiver: ^3.2.1
  cli_util: ^0.3.5
  yaml: ^3.1.1
  hex: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
